version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && ng serve --host 0.0.0.0 --poll 2000"

networks:
  default:
    driver: bridge 